### ISSUE TITLE
Exited status

### ISSUE THREAD

**Issue by mika756** [poseidon-network/qlauncher-linux#9]
e99ebab702a9        7b52860fcf04                                                 "/bin/sh -c 'nginx -…"   24 hours ago        Exited (137) 24 hours ago                                                                                k8s_nginx_nginx-x86-443-nml7b_default_8adb2ca7-5c49-4294-a61f-c563f32944aa_0

If there is exited status, surely port 443 or 32443,32446 will close, how to order the status is not exited 
![IMG_20200622_214917_081](https://user-images.githubusercontent.com/24768969/85301999-c6d1ee00-b4d2-11ea-8523-52d357ac5cb4.jpg)

**Comment by coderkk** [comment]
When the exited status show there have fews possibility
- the ports have been used or blocked.
- hardware no enough resources example memory or storage
- and etc.

Normally qlauncher will try to self recovery by create another service. If you see another nginx-x86-443 is up, you can ignore the exit status because it been recovered by this service.

If still cannot, maybe you can try restart the qlauncher.
